version: "3.8"

services:
  chatbot:
    image: mateogiraldo/chatbot:latest
    environment:
      - N8N_BASE_URL=https://sswebhookss.mateogiraldo.online
      - N8N_WEBHOOK_PATH=/webhook/e26fc1da-1f0b-4391-9e8b-19736d89b924
      - N8N_GEMINI_WEBHOOK_PATH=/webhook/83d9324f-cab7-442c-8af8-f8c41b3078c2
      - N8N_FILE_UPLOAD_PATH=/form/82848bc4-5ea2-4e5a-8bb6-3c09b94a8c5d
      - N8N_GEMINI_FILE_UPLOAD_PATH=/form/89c24c04-11c0-49b8-940b-df8b3a361a53
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    networks:
      - traefik_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chatbot.rule=Host(`sschatss.mateogiraldo.online`)"
        - "traefik.http.routers.chatbot.entrypoints=websecure"
        - "traefik.http.routers.chatbot.tls.certresolver=letsencrypt"
        - "traefik.http.services.chatbot.loadbalancer.server.port=3000"
        - "traefik.http.routers.chatbot-http.rule=Host(`sschatss.mateogiraldo.online`)"
        - "traefik.http.routers.chatbot-http.entrypoints=web"
        - "traefik.http.routers.chatbot-http.middlewares=https-redirect"
        - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

networks:
  traefik_public:
    external: true
